export const TOOL = {
  displayName: "SpecMarten",
  cliName: "specmarten",
  configFile: ".specmarten.json",
  dataDir: "specmarten",
  version: "0.1.2"
} as const;

export const GENERATED_HEADER =
  "<!-- Generated by SpecMarten. Do not edit by hand; tell the AI maintainer what should change. -->";
